# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: imu.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import pose_pb2 as pose__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='imu.proto',
  package='COWA.SensorMsg',
  syntax='proto2',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\timu.proto\x12\x0e\x43OWA.SensorMsg\x1a\npose.proto\"\xf6\x04\n\x03Imu\x12\x11\n\ttimestamp\x18\x01 \x01(\x04\x12\x10\n\x08sequence\x18\x02 \x01(\r\x12%\n\x07\x61ngular\x18\x03 \x01(\x0b\x32\x14.COWA.NavMsg.Point3D\x12*\n\x0c\x61\x63\x63\x65leration\x18\x04 \x01(\x0b\x32\x14.COWA.NavMsg.Point3D\x12,\n\x0borientation\x18\x05 \x01(\x0b\x32\x17.COWA.NavMsg.Quaternion\x12\x32\n\ncovariance\x18\x06 \x01(\x0b\x32\x1e.COWA.SensorMsg.Imu.Covariance\x12\x19\n\x11\x65rror_frame_count\x18\n \x01(\r\x12\r\n\x05model\x18\x0b \x01(\x0c\x12\x12\n\nlatency_ms\x18\x0c \x01(\x05\x12)\n\x06status\x18\r \x01(\x0e\x32\x19.COWA.SensorMsg.Imu.State\x12\x13\n\x0btemperature\x18\x0e \x01(\x02\x12\x11\n\ttransform\x18\x0f \x03(\x02\x12\x12\n\nintrinsics\x18\x10 \x03(\x02\x12#\n\x0fparent_frame_id\x18\x11 \x01(\t:\n/base_link\x12\x16\n\x08\x66rame_id\x18\x12 \x01(\t:\x04/imu\x1a_\n\nCovariance\x12%\n\x07\x61ngular\x18\x01 \x01(\x0b\x32\x14.COWA.NavMsg.Point3D\x12*\n\x0c\x61\x63\x63\x65leration\x18\x02 \x01(\x0b\x32\x14.COWA.NavMsg.Point3D\"R\n\x05State\x12\x06\n\x02OK\x10\x00\x12\r\n\tLOST_BOTH\x10\x01\x12\n\n\x06LOST_A\x10\x02\x12\n\n\x06LOST_B\x10\x03\x12\r\n\tTEMP_HIGH\x10\x04\x12\x0b\n\x07TIMEOUT\x10\x05'
  ,
  dependencies=[pose__pb2.DESCRIPTOR,])



_IMU_STATE = _descriptor.EnumDescriptor(
  name='State',
  full_name='COWA.SensorMsg.Imu.State',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='OK', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='LOST_BOTH', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='LOST_A', index=2, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='LOST_B', index=3, number=3,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='TEMP_HIGH', index=4, number=4,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='TIMEOUT', index=5, number=5,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=590,
  serialized_end=672,
)
_sym_db.RegisterEnumDescriptor(_IMU_STATE)


_IMU_COVARIANCE = _descriptor.Descriptor(
  name='Covariance',
  full_name='COWA.SensorMsg.Imu.Covariance',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='angular', full_name='COWA.SensorMsg.Imu.Covariance.angular', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='acceleration', full_name='COWA.SensorMsg.Imu.Covariance.acceleration', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=493,
  serialized_end=588,
)

_IMU = _descriptor.Descriptor(
  name='Imu',
  full_name='COWA.SensorMsg.Imu',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='timestamp', full_name='COWA.SensorMsg.Imu.timestamp', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='sequence', full_name='COWA.SensorMsg.Imu.sequence', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='angular', full_name='COWA.SensorMsg.Imu.angular', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='acceleration', full_name='COWA.SensorMsg.Imu.acceleration', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='orientation', full_name='COWA.SensorMsg.Imu.orientation', index=4,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='covariance', full_name='COWA.SensorMsg.Imu.covariance', index=5,
      number=6, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='error_frame_count', full_name='COWA.SensorMsg.Imu.error_frame_count', index=6,
      number=10, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='model', full_name='COWA.SensorMsg.Imu.model', index=7,
      number=11, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='latency_ms', full_name='COWA.SensorMsg.Imu.latency_ms', index=8,
      number=12, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='status', full_name='COWA.SensorMsg.Imu.status', index=9,
      number=13, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='temperature', full_name='COWA.SensorMsg.Imu.temperature', index=10,
      number=14, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='transform', full_name='COWA.SensorMsg.Imu.transform', index=11,
      number=15, type=2, cpp_type=6, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='intrinsics', full_name='COWA.SensorMsg.Imu.intrinsics', index=12,
      number=16, type=2, cpp_type=6, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='parent_frame_id', full_name='COWA.SensorMsg.Imu.parent_frame_id', index=13,
      number=17, type=9, cpp_type=9, label=1,
      has_default_value=True, default_value=b"/base_link".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='frame_id', full_name='COWA.SensorMsg.Imu.frame_id', index=14,
      number=18, type=9, cpp_type=9, label=1,
      has_default_value=True, default_value=b"/imu".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[_IMU_COVARIANCE, ],
  enum_types=[
    _IMU_STATE,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=42,
  serialized_end=672,
)

_IMU_COVARIANCE.fields_by_name['angular'].message_type = pose__pb2._POINT3D
_IMU_COVARIANCE.fields_by_name['acceleration'].message_type = pose__pb2._POINT3D
_IMU_COVARIANCE.containing_type = _IMU
_IMU.fields_by_name['angular'].message_type = pose__pb2._POINT3D
_IMU.fields_by_name['acceleration'].message_type = pose__pb2._POINT3D
_IMU.fields_by_name['orientation'].message_type = pose__pb2._QUATERNION
_IMU.fields_by_name['covariance'].message_type = _IMU_COVARIANCE
_IMU.fields_by_name['status'].enum_type = _IMU_STATE
_IMU_STATE.containing_type = _IMU
DESCRIPTOR.message_types_by_name['Imu'] = _IMU
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Imu = _reflection.GeneratedProtocolMessageType('Imu', (_message.Message,), {

  'Covariance' : _reflection.GeneratedProtocolMessageType('Covariance', (_message.Message,), {
    'DESCRIPTOR' : _IMU_COVARIANCE,
    '__module__' : 'imu_pb2'
    # @@protoc_insertion_point(class_scope:COWA.SensorMsg.Imu.Covariance)
    })
  ,
  'DESCRIPTOR' : _IMU,
  '__module__' : 'imu_pb2'
  # @@protoc_insertion_point(class_scope:COWA.SensorMsg.Imu)
  })
_sym_db.RegisterMessage(Imu)
_sym_db.RegisterMessage(Imu.Covariance)


# @@protoc_insertion_point(module_scope)
