# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: robot_sensors.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='robot_sensors.proto',
  package='COWA.HumanoidMsg',
  syntax='proto2',
  serialized_pb=_b('\n\x13robot_sensors.proto\x12\x10\x43OWA.HumanoidMsg\"\"\n\x0ePressureSensor\x12\x10\n\x08pressure\x18\x01 \x01(\x02\"\x1e\n\x0cTorqueSensor\x12\x0e\n\x06torque\x18\x01 \x01(\x02\"\x93\x02\n\nArmRawData\x12\x36\n\x0eshoulder_pitch\x18\x01 \x01(\x0b\x32\x1e.COWA.HumanoidMsg.TorqueSensor\x12\x35\n\rshoulder_roll\x18\x02 \x01(\x0b\x32\x1e.COWA.HumanoidMsg.TorqueSensor\x12\x31\n\tupper_arm\x18\x03 \x01(\x0b\x32\x1e.COWA.HumanoidMsg.TorqueSensor\x12\x33\n\tlower_arm\x18\x04 \x01(\x0b\x32 .COWA.HumanoidMsg.PressureSensor\x12.\n\x06wrists\x18\x05 \x01(\x0b\x32\x1e.COWA.HumanoidMsg.TorqueSensor\"u\n\x0cWaistRawData\x12\x32\n\nwaist_roll\x18\x01 \x01(\x0b\x32\x1e.COWA.HumanoidMsg.TorqueSensor\x12\x31\n\twaist_yaw\x18\x02 \x01(\x0b\x32\x1e.COWA.HumanoidMsg.TorqueSensor\"\xc9\x02\n\nLegRawData\x12\x30\n\x08hip_roll\x18\x01 \x01(\x0b\x32\x1e.COWA.HumanoidMsg.TorqueSensor\x12/\n\x07hip_yaw\x18\x02 \x01(\x0b\x32\x1e.COWA.HumanoidMsg.TorqueSensor\x12\x35\n\x0bthigh_front\x18\x03 \x01(\x0b\x32 .COWA.HumanoidMsg.PressureSensor\x12\x34\n\nthigh_back\x18\x04 \x01(\x0b\x32 .COWA.HumanoidMsg.PressureSensor\x12\x34\n\ncalve_left\x18\x05 \x01(\x0b\x32 .COWA.HumanoidMsg.PressureSensor\x12\x35\n\x0b\x63\x61lve_right\x18\x06 \x01(\x0b\x32 .COWA.HumanoidMsg.PressureSensor\"\xa5\x02\n\rSensorRawData\x12\x11\n\ttimestamp\x18\x01 \x01(\x04\x12\x10\n\x08sequence\x18\x02 \x01(\r\x12.\n\x08left_arm\x18\x03 \x01(\x0b\x32\x1c.COWA.HumanoidMsg.ArmRawData\x12/\n\tright_arm\x18\x04 \x01(\x0b\x32\x1c.COWA.HumanoidMsg.ArmRawData\x12-\n\x05waist\x18\x05 \x01(\x0b\x32\x1e.COWA.HumanoidMsg.WaistRawData\x12.\n\x08left_leg\x18\x06 \x01(\x0b\x32\x1c.COWA.HumanoidMsg.LegRawData\x12/\n\tright_leg\x18\x07 \x01(\x0b\x32\x1c.COWA.HumanoidMsg.LegRawData')
)




_PRESSURESENSOR = _descriptor.Descriptor(
  name='PressureSensor',
  full_name='COWA.HumanoidMsg.PressureSensor',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='pressure', full_name='COWA.HumanoidMsg.PressureSensor.pressure', index=0,
      number=1, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=41,
  serialized_end=75,
)


_TORQUESENSOR = _descriptor.Descriptor(
  name='TorqueSensor',
  full_name='COWA.HumanoidMsg.TorqueSensor',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='torque', full_name='COWA.HumanoidMsg.TorqueSensor.torque', index=0,
      number=1, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=77,
  serialized_end=107,
)


_ARMRAWDATA = _descriptor.Descriptor(
  name='ArmRawData',
  full_name='COWA.HumanoidMsg.ArmRawData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='shoulder_pitch', full_name='COWA.HumanoidMsg.ArmRawData.shoulder_pitch', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='shoulder_roll', full_name='COWA.HumanoidMsg.ArmRawData.shoulder_roll', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='upper_arm', full_name='COWA.HumanoidMsg.ArmRawData.upper_arm', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='lower_arm', full_name='COWA.HumanoidMsg.ArmRawData.lower_arm', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='wrists', full_name='COWA.HumanoidMsg.ArmRawData.wrists', index=4,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=110,
  serialized_end=385,
)


_WAISTRAWDATA = _descriptor.Descriptor(
  name='WaistRawData',
  full_name='COWA.HumanoidMsg.WaistRawData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='waist_roll', full_name='COWA.HumanoidMsg.WaistRawData.waist_roll', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='waist_yaw', full_name='COWA.HumanoidMsg.WaistRawData.waist_yaw', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=387,
  serialized_end=504,
)


_LEGRAWDATA = _descriptor.Descriptor(
  name='LegRawData',
  full_name='COWA.HumanoidMsg.LegRawData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='hip_roll', full_name='COWA.HumanoidMsg.LegRawData.hip_roll', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='hip_yaw', full_name='COWA.HumanoidMsg.LegRawData.hip_yaw', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='thigh_front', full_name='COWA.HumanoidMsg.LegRawData.thigh_front', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='thigh_back', full_name='COWA.HumanoidMsg.LegRawData.thigh_back', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='calve_left', full_name='COWA.HumanoidMsg.LegRawData.calve_left', index=4,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='calve_right', full_name='COWA.HumanoidMsg.LegRawData.calve_right', index=5,
      number=6, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=507,
  serialized_end=836,
)


_SENSORRAWDATA = _descriptor.Descriptor(
  name='SensorRawData',
  full_name='COWA.HumanoidMsg.SensorRawData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='timestamp', full_name='COWA.HumanoidMsg.SensorRawData.timestamp', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='sequence', full_name='COWA.HumanoidMsg.SensorRawData.sequence', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='left_arm', full_name='COWA.HumanoidMsg.SensorRawData.left_arm', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='right_arm', full_name='COWA.HumanoidMsg.SensorRawData.right_arm', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='waist', full_name='COWA.HumanoidMsg.SensorRawData.waist', index=4,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='left_leg', full_name='COWA.HumanoidMsg.SensorRawData.left_leg', index=5,
      number=6, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='right_leg', full_name='COWA.HumanoidMsg.SensorRawData.right_leg', index=6,
      number=7, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=839,
  serialized_end=1132,
)

_ARMRAWDATA.fields_by_name['shoulder_pitch'].message_type = _TORQUESENSOR
_ARMRAWDATA.fields_by_name['shoulder_roll'].message_type = _TORQUESENSOR
_ARMRAWDATA.fields_by_name['upper_arm'].message_type = _TORQUESENSOR
_ARMRAWDATA.fields_by_name['lower_arm'].message_type = _PRESSURESENSOR
_ARMRAWDATA.fields_by_name['wrists'].message_type = _TORQUESENSOR
_WAISTRAWDATA.fields_by_name['waist_roll'].message_type = _TORQUESENSOR
_WAISTRAWDATA.fields_by_name['waist_yaw'].message_type = _TORQUESENSOR
_LEGRAWDATA.fields_by_name['hip_roll'].message_type = _TORQUESENSOR
_LEGRAWDATA.fields_by_name['hip_yaw'].message_type = _TORQUESENSOR
_LEGRAWDATA.fields_by_name['thigh_front'].message_type = _PRESSURESENSOR
_LEGRAWDATA.fields_by_name['thigh_back'].message_type = _PRESSURESENSOR
_LEGRAWDATA.fields_by_name['calve_left'].message_type = _PRESSURESENSOR
_LEGRAWDATA.fields_by_name['calve_right'].message_type = _PRESSURESENSOR
_SENSORRAWDATA.fields_by_name['left_arm'].message_type = _ARMRAWDATA
_SENSORRAWDATA.fields_by_name['right_arm'].message_type = _ARMRAWDATA
_SENSORRAWDATA.fields_by_name['waist'].message_type = _WAISTRAWDATA
_SENSORRAWDATA.fields_by_name['left_leg'].message_type = _LEGRAWDATA
_SENSORRAWDATA.fields_by_name['right_leg'].message_type = _LEGRAWDATA
DESCRIPTOR.message_types_by_name['PressureSensor'] = _PRESSURESENSOR
DESCRIPTOR.message_types_by_name['TorqueSensor'] = _TORQUESENSOR
DESCRIPTOR.message_types_by_name['ArmRawData'] = _ARMRAWDATA
DESCRIPTOR.message_types_by_name['WaistRawData'] = _WAISTRAWDATA
DESCRIPTOR.message_types_by_name['LegRawData'] = _LEGRAWDATA
DESCRIPTOR.message_types_by_name['SensorRawData'] = _SENSORRAWDATA
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

PressureSensor = _reflection.GeneratedProtocolMessageType('PressureSensor', (_message.Message,), dict(
  DESCRIPTOR = _PRESSURESENSOR,
  __module__ = 'robot_sensors_pb2'
  # @@protoc_insertion_point(class_scope:COWA.HumanoidMsg.PressureSensor)
  ))
_sym_db.RegisterMessage(PressureSensor)

TorqueSensor = _reflection.GeneratedProtocolMessageType('TorqueSensor', (_message.Message,), dict(
  DESCRIPTOR = _TORQUESENSOR,
  __module__ = 'robot_sensors_pb2'
  # @@protoc_insertion_point(class_scope:COWA.HumanoidMsg.TorqueSensor)
  ))
_sym_db.RegisterMessage(TorqueSensor)

ArmRawData = _reflection.GeneratedProtocolMessageType('ArmRawData', (_message.Message,), dict(
  DESCRIPTOR = _ARMRAWDATA,
  __module__ = 'robot_sensors_pb2'
  # @@protoc_insertion_point(class_scope:COWA.HumanoidMsg.ArmRawData)
  ))
_sym_db.RegisterMessage(ArmRawData)

WaistRawData = _reflection.GeneratedProtocolMessageType('WaistRawData', (_message.Message,), dict(
  DESCRIPTOR = _WAISTRAWDATA,
  __module__ = 'robot_sensors_pb2'
  # @@protoc_insertion_point(class_scope:COWA.HumanoidMsg.WaistRawData)
  ))
_sym_db.RegisterMessage(WaistRawData)

LegRawData = _reflection.GeneratedProtocolMessageType('LegRawData', (_message.Message,), dict(
  DESCRIPTOR = _LEGRAWDATA,
  __module__ = 'robot_sensors_pb2'
  # @@protoc_insertion_point(class_scope:COWA.HumanoidMsg.LegRawData)
  ))
_sym_db.RegisterMessage(LegRawData)

SensorRawData = _reflection.GeneratedProtocolMessageType('SensorRawData', (_message.Message,), dict(
  DESCRIPTOR = _SENSORRAWDATA,
  __module__ = 'robot_sensors_pb2'
  # @@protoc_insertion_point(class_scope:COWA.HumanoidMsg.SensorRawData)
  ))
_sym_db.RegisterMessage(SensorRawData)


# @@protoc_insertion_point(module_scope)
